### ISSUE TITLE
10m populated places: Name for Rangoon should be anglicized as "Yangon"

### ISSUE THREAD

**Issue by elliotap** [nvkelso/natural-earth-vector#467] opened 2021-01-14 22:53 UTC
For feature 1159151477, name=Rangoon, namealt=Yangon, and name_en=Yangon. Yangon appears to be the common spelling, although Rangoon may be preferred by American/British foreign policy institutions. 

https://en.wikipedia.org/wiki/Yangon
https://www.bbc.com/news/magazine-16000467

**Comment by nvkelso** [comment] 2021-01-14 23:08
Maybe?

We already have `Yangon` as the name_alt. But I do recognize the inconsistency `between` name and `name_en`.

Perhaps the answer is to make `Yangon` name and `Rangoon` as name_parenthetical as it is the conventional / historic spelling for the place. Sounds like it changed a while ago, but this change was new to me.

**Comment by elliotap** [comment] 2021-01-14 23:38
I've seen the country often labeled as Myanmar (Burma) so the parallel structure would make a lot of sense - I did some reading on the geopolitics of the naming/spelling conventions a few months ago but still don't have a clear understanding of the stakes of the issue. 

For reference also, this is their order on the renaming of places: https://www.burmalibrary.org/sites/burmalibrary.org/files/obl/docs25/1989_06_18_SLORC_No.15-en.pdf

and a beltway analysis, for what its worth:
https://webcache.googleusercontent.com/search?q=cache%3AorQb5-vPMMgJ%3Ahttps%3A%2F%2Fwww.washingtonpost.com%2Fnews%2Fworldviews%2Fwp%2F2012%2F11%2F19%2Fwhy-its-such-a-big-deal-that-obama-said-myanmar-rather-than-burma%2F+&cd=20&hl=en&ct=clnk&gl=us

**Comment by nvkelso** [comment] 2021-02-11 06:14
Duplicate of https://github.com/nvkelso/natural-earth-vector/issues/381, which is already scheduled for release. Closing.

**Closed by nvkelso** 2021-02-11 06:14 UTC
