### ISSUE TITLE
Unable to download 10m minor island

### ISSUE THREAD

**Issue by xiaojuanjuan-cn** [nvkelso/natural-earth-vector#588] opened 2021-09-12 08:30 UTC

**Comment by almccon** [comment] 2021-09-13 17:39
Maybe the same issue as #581? See more discussion there.

**Comment by nvkelso** [comment] 2021-09-15 06:49
Dupe of https://github.com/nvkelso/natural-earth-vector/issues/581.

**Closed by nvkelso** 2021-09-15 06:49 UTC
