### ISSUE TITLE
Issues Downloading Any Raster Data from Natural Earth (Applies to 10m and 50m scale)

### ISSUE THREAD

**Issue by DaikonSt** [nvkelso/natural-earth-vector#600] opened 2021-09-28 20:03 UTC
Hi,

Been trying to download any of the raster data available on the site, and eventually the page just times out. I've tried both 10m and 50m scale datasets, and also tried older versions, where available (sometimes have to do this to get vector data sets to download). Nothing seems to be working.

Any help would be appreciated.

Thanks!

Christina

**Comment by nvkelso** [comment] 2021-09-29 03:05
Duplicate of https://github.com/nvkelso/natural-earth-vector/issues/581.

There's a [GIST](https://github.com/nvkelso/natural-earth-vector/issues/581#issuecomment-916250782) showing where to find the files in the meantime.

The raster files are also in the S3 buckets.

**Closed** 2021-09-29 03:05 UTC
