### ISSUE TITLE
10m admin1: missing territory for US-VA

### ISSUE THREAD

**Issue by MLWorley** [nvkelso/natural-earth-vector#743] opened 2022-05-27 03:19 UTC
There are a couple of noticeable chunks of land missing in ne_10m_admin_1_states_provinces, if you look at it against the background of, say, ne_10m_ocean and you're looking in the right places.

1) The eastern shore of Virginia (US-VA) in the United States is missing. In real life it is detached from the mainland of Virginia, but it's actually a peninsula separated from mainland Virginia by Chesapeake Bay rather than an island. In any case I *think* it is too big to have fallen out as a minor island even if it were an island.

~~2) Multiple subdivisions - that is, municipalities - of the Aland Islands are missing - if you look near the capital (Mariehamn) you'll notice that the biggest island there is missing a big chunk, and if you compare the list of municipality subdivisions for the Aland Islands to those actually present in ne_10m_admin_1_states_provinces, a few are missing.~~

Both these pieces of land show up in the ne_10m_admin_0_countries the last time I looked.

**Comment by MLWorley** [comment] 2022-05-27 12:03
~~Another missing subdivision is the United States Minor Outlying Islands subdivision of Kingman Reef. It shows up in ne_10m_admin_0_countries, I think, but not ne_10m_admin_1_states_provinces. I realize it's pretty small but so are the other UM entries and they got through. (I mention it because I wouldn't think it's a minor islands size filter causing it to be dropped given that the others got in.)~~

**Comment by MLWorley** [comment] 2022-06-06 16:35
~~Missing subdivisions of the Aland Islands are missing, specifically these 5 (names given in ASCII):~~

- ~~Finstrom~~
- ~~Geta~~
- ~~Hammarland~~
- ~~Saltvik~~
- ~~Sund~~

~~In this case, the land itself is missing; it's not a case of the physical land being present but just organized incorrectly.~~

~~GADM (https://gadm.org/maps/ALA_1.html) appears to have all the Aland subdivisions present, if that would be of any help in getting the missing divisions updated.~~

**Comment by nvkelso** [comment] 2022-06-11 20:29
To better track the work, I've kept this issue focused on the first topic (missing US-VA land chunks in DelMarVa penn.) and split off the other two topics into #764 (Aland) and #765 (Kingman Reef).

**Comment by nvkelso** [comment] 2022-06-11 20:31
@MLWorley Can you confirm you're on the latest v5.x series of Natural Earth, please? This issue was present in v4 but was fixed via https://github.com/nvkelso/natural-earth-vector/issues/355 in v5. I can't reproduce it in v5. If you can, please reopen the issue.

**Closed by nvkelso** 2022-06-11 20:31 UTC

**Comment by MLWorley** [comment] 2022-06-13 14:54
I'm fine with tracking the issues separately as appropriate.

I'll have to hold off on confirming / denying whether the US-VA issue shows up in my latest copy until later today, sorry about the delay.

**Comment by MLWorley** [comment] 2022-06-14 11:22
You're right; the US-VA issue seems to be fixed. Thank you.
