### ISSUE TITLE
India border Issue

### ISSUE THREAD

**Issue by Sakshimittal95** [nvkelso/natural-earth-vector#716] opened 2022-04-26 15:48 UTC
Please rectify India's Border in all of the layers on your portal. I have requested before but issue has not been resolved. Jammu & Kashmir is an integral part of India. Every country is accepting this fact and some of them have changed their maps too.  Not changing the map even after multiple requests, is like you are challenging the fact. Pakistan has illegally occupied our territory which we will take back soon. if someone illegally captured your home, doesn't mean that he is the owner. Understand the fact and rectify the errors asap. I will post this on social media next time.
https://www.naturalearthdata.com/downloads/10m-cultural-vectors/

**Comment by KalamkarVA** [comment] 2022-10-09 19:32
I fully support and demand for immediately rectifying the error in data for India Map. Jammu and Kashmir are the integral parts of India, they are wrongly shown in Pakistan.

**Comment by nvkelso** [comment] 2022-10-09 22:53
Duplicate of #702, closing.

**Closed by nvkelso** 2022-10-09 22:53 UTC
