### ISSUE TITLE
Different feature counts for ne_10m_populated_places and ne_10m_populated_places_simple.shp

### ISSUE THREAD

**Issue by pnorman** [nvkelso/natural-earth-vector#185] opened 2017-01-20 21:13 UTC
The command `diff -u3 --color=always  <(ogrinfo ne_10m_populated_places.shp -so -al)  <(ogrinfo ne_10m_populated_places_simple.shp -so -al)` tells me that ne_10m_populated_places has 7343 features while ne_10m_populated_places_simple has 7322. Should be the same?

Raw output is

```diff
--- /dev/fd/63  2017-01-20 13:09:42.071170500 -0800
+++ /dev/fd/62  2017-01-20 13:09:42.071170500 -0800
@@ -1,107 +1,49 @@
-INFO: Open of `ne_10m_populated_places.shp'
+INFO: Open of `ne_10m_populated_places_simple.shp'
       using driver `ESRI Shapefile' successful.

-Layer name: ne_10m_populated_places
-Metadata:
-  DBF_DATE_LAST_UPDATE=2013-10-06
+Layer name: ne_10m_populated_places_simple
 Geometry: Point
-Feature Count: 7343
+Feature Count: 7322
 Extent: (-179.589979, -90.000000) - (179.383304, 82.483323)
...
```

Edit - fixed misplaced space

**Comment by nvkelso** [comment] 2017-07-30 05:10
Can't reproduce.

**Comment by pnorman** [comment] 2017-07-31 01:22
I still get this with fresh downloads. Relevant console log to reproduce

```
curl -OL 'http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/cultural/ne_10m_populated_places.zip'
curl -OL 'http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/cultural/ne_10m_populated_places_simple.zip'
unzip ne_10m_populated_places.zip
unzip ne_10m_populated_places_simple.zip
diff -u3 --color=always  <(ogrinfo ne_10m_populated_places.shp -so -al)  <(ogrinfo ne_10m_populated_places_simple.shp -so -al) | head -n 30
```

Output is

```diff
-INFO: Open of `ne_10m_populated_places.shp'
+INFO: Open of `ne_10m_populated_places_simple.shp'
       using driver `ESRI Shapefile' successful.

-Layer name: ne_10m_populated_places
-Metadata:
-  DBF_DATE_LAST_UPDATE=2013-10-06
+Layer name: ne_10m_populated_places_simple
 Geometry: Point
-Feature Count: 7343
+Feature Count: 7322
 Extent: (-179.589979, -90.000000) - (179.383304, 82.483323)
 Layer SRS WKT:
 GEOGCS["GCS_WGS_1984",
...
```

**Comment by nvkelso** [comment] 2017-07-31 04:15
Hmm. The source files in the repo don't have this problem when counting with QGIS, so either there is a inconsistency between that app and GDAL, or it's a packaging problem for the downloads on the site.

**Comment by pnorman** [comment] 2017-07-31 20:39
Cloning with git I get

```diff
--- /dev/fd/63  2017-07-31 13:38:34.065973223 -0700
+++ /dev/fd/62  2017-07-31 13:38:34.065973223 -0700
@@ -1,9 +1,7 @@
-INFO: Open of `ne_10m_populated_places.shp'
+INFO: Open of `ne_10m_populated_places_simple.shp'
       using driver `ESRI Shapefile' successful.

-Layer name: ne_10m_populated_places
-Metadata:
-  DBF_DATE_LAST_UPDATE=2017-07-30
+Layer name: ne_10m_populated_places_simple
 Geometry: Point
 Feature Count: 7343
 Extent: (-179.589979, -90.000000) - (179.383304, 82.483323)
@@ -12,97 +10,40 @@
     DATUM["WGS_1984",
         SPHEROID["WGS_84",6378137.0,298.257223563]],
     PRIMEM["Greenwich",0.0],
```

So the problem is that git is different from the official releases

**Comment by nvkelso** [comment] 2017-07-31 21:14
Adding this back to v4 milestone for final pre-flight packaging checklist.

**Comment by nvkelso** [comment] 2017-08-13 02:40
Verified the new assets correctly have the same feature counts. Closing.

(Requires final release.)

**Closed by nvkelso** 2017-08-13 02:40 UTC
Labels: packaging
