### ISSUE TITLE
Dead URL

### ISSUE THREAD

**Issue by jheaff1** [nvkelso/natural-earth-vector#528] opened 2021-04-28 10:46 UTC
Hi,

It seems the following URL is broken:

https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/110m/cultural/ne_110m_admin_0_boundary_lines_land.zip

This is the hyperlink of the "Download country boundaries" text in the "Admin 0 - Boundary Lines" section of https://www.naturalearthdata.com/downloads/110m-cultural-vectors/

**Comment by nvkelso** [comment] 2021-04-30 04:55
@jheaff1 @bienflorencia I can't reproduce this. Is it still a problem for you?

**Comment by matkoniecz** [comment] 2021-04-30 05:54
It also works for me.

**Comment by nvkelso** [comment] 2021-04-30 06:10
It does look like the site theme is borked again, so even though downloads work might point to a different problem?

**Comment by bodkan** [comment] 2021-04-30 08:16
Hello, I think I encountered the same (or a related?) problem. A couple of days ago tests of my R package (which uses Natural Earth data via the `rnaturalearth` package) started failing.

The problem:

```{r}
> rnaturalearth::ne_download()
trying URL 'http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/110m/cultural/ne_110m_admin_0_countries.zip'
Error in utils::download.file(file.path(address), zip_file <- tempfile()) : 
  cannot open URL 'http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/110m/cultural/ne_110m_admin_0_countries.zip'
In addition: Warning message:
In utils::download.file(file.path(address), zip_file <- tempfile()) :
  cannot open URL 'http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/110m/cultural/ne_110m_admin_0_countries.zip': 
HTTP status was '500 Internal Server Error'
```

Same happens when using `wget`:

```
wget http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/110m/cultural/ne_110m_admin_0_countries.zi
```

Any chance this could be the same issue that was reported (and then solved) [here](https://github.com/nvkelso/natural-earth-vector/issues/434)?

Thanks!

**Comment by jheaff1** [comment] 2021-04-30 15:29
@nvkelso  I can no longer reproduce this issue

**Comment by MrTakuah** [comment] 2021-04-30 17:19
I am still seeing this issue trying to download some natural earth data:

`trying URL 'http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/cultural/ne_10m_admin_1_states_provinces_lakes.zip'
cannot open URL 'http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/cultural/ne_10m_admin_1_states_provinces_lakes.zip': HTTP status was '500 Internal Server Error'Error in utils::download.file(file.path(address), zip_file <- tempfile()) : 
  cannot open URL 'http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/cultural/ne_10m_admin_1_states_provinces_lakes.zip'`

**Comment by matkoniecz** [comment] 2021-05-01 07:03
opening download at https://www.naturalearthdata.com/downloads/10m-cultural-vectors/ link worked fine (in FF) but is reported to be downloaded from https://naciscdn.org/naturalearth/10m/cultural/ne_10m_cultural_building_blocks_all.zip from 

`curl https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/cultural/ne_10m_cultural_building_blocks_all.zip` fetches page with `<div class="wp-die-message"><p>There has been a critical error on your website.</p><p><a href="https://wordpress.org/support/article/debugging-in-wordpress/">Learn more about debugging in WordPress.</a></p></div>`

similarly opening https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/cultural/ne_10m_cultural_building_blocks_all.zip in FF brings error page.

**Comment by vayunalapati** [comment] 2021-05-07 04:12
For some reason when I click the link for https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/110m/cultural/ne_110m_admin_0_boundary_lines_land.zip I am able to download the file but if I attempt to paste it into my url bar it redirects me to the following page 
![image](https://user-images.githubusercontent.com/77701570/117396858-db3f8f00-aec8-11eb-83c0-8714710fb6ec.png) not sure how to resolve this since attempting to `curl` the file results in an Internal Server Error.

**Comment by nvkelso** [comment] 2021-05-07 05:07
How about this link?

- http://naturalearth.s3.amazonaws.com/110m_cultural/ne_110m_admin_0_boundary_lines_land.zip

All the other files exist there now, too as part of https://github.com/nvkelso/natural-earth-vector/issues/445. 

I'm also investigating why the main site is having problems, but feel free to use the S3 links instead, they are hosted by AWS as part of their public dataset program and will be kept up to date as new versions of Natural Earth are published.

**Comment by vayunalapati** [comment] 2021-05-07 05:10
Works perfectly thanks for your help!

**Comment by nvkelso** [comment] 2021-05-07 05:15
The main site should be fixed (for now) – the borked site theme has been restored and the downloads should work again. There are some PHP issues to work out medium term.

**Closed** 2021-05-07 05:18 UTC
