### ISSUE TITLE
Kazakhstan in ne_10m_admin_0_sovereignty

### ISSUE THREAD

**Issue by josh26turner** [nvkelso/natural-earth-vector#354] opened 2020-06-25 00:39 UTC
In ne_10m_admin_0_sovereignty the whole of Kazakhstan is labelled as the Baikonour Cosmodrone

**Comment by nvkelso** [comment] 2021-02-02 07:27
Thanks for the report @josh26turner!

This is a duplicate of https://github.com/nvkelso/natural-earth-vector/issues/313, closing.

**Closed** 2021-02-11 06:44 UTC
