### ISSUE TITLE
France has ISO3166 Alpha-3 of -99 (and others)

### ISSUE THREAD

**Issue by mapadofu** [nvkelso/natural-earth-vector#480] opened 2021-02-26 01:02 UTC
I just downloaded `ne_110m_admin_0_countries.zip` today. (4.1.0)

I'm seeing that the record for France in `ne_110m_admin_0_countries.shp`

Has some invalid fields
- `ISO_A3 = -99`
- `ISO_A2 = -99`
- `WIKIPEDIA = -99`
- `LASTCENSUS = -99`
- `ADM0_A3_UN =  -99`
-  `ADM0_A3_WB = -99`
- `TINY = -99` 

I'm using the data in python like so:

```
import cartopy.io.shapereader as shpreader
fname = "./shape_files/ne_110m_admin_0_countries.shp"
records = shpreader.Reader(fname).records()
france = [x for x in records if x.attributes['NAME_EN'] == 'France'][0]
print(france)
print(france.attributes['ISO_A3'])
```

**Comment by nvkelso** [comment] 2021-02-26 01:25
Duplicate of https://github.com/nvkelso/natural-earth-vector/issues/268#issuecomment-778832542.

**Closed by nvkelso** 2021-02-26 01:25 UTC
