### ISSUE TITLE
Time zones for Russia

### ISSUE THREAD

**Issue by romanovgleb** [nvkelso/natural-earth-vector#888] opened 2024-01-20 08:34 UTC
Hey there! Thanks for a dataset - it's very helpful.

However, there's a mistake in at least one place: the polygon containing Moscow displays its Timezone to be UTC+4 instead of UTC+3 which it should be

Would appreciate the correction. Thanks!

**Comment by hpvd** [comment] 2024-01-24 10:26
possibly related to:
https://github.com/nvkelso/natural-earth-vector/issues/864

**Comment by nvkelso** [comment] 2024-01-28 22:20
Duplicate of #864, closing (thanks @hpvd)

**Closed as completed by nvkelso** 2024-01-28 22:20 UTC
