### ISSUE TITLE
Natural Earth 1:10m Physical Vectors Download

### ISSUE THREAD

**Issue by Craig-Smith-Anemoi** [nvkelso/natural-earth-vector#593] opened 2021-09-15 15:46 UTC
I'm attempting to download all 10m physical themes using chrome and the file downloads consistety time out. I was hoping there was an alternate way of obtaining these, perhaps via email? I have checked various internet connections and it certainly is not a connection issue.

**Comment by i-s-o** [comment] 2021-09-15 19:43
Duplicate of #581

**Closed** 2021-09-17 07:09 UTC
