### ISSUE TITLE
Download is timing out

### ISSUE THREAD

**Issue by ajbraudev** [nvkelso/natural-earth-vector#578] opened 2021-09-02 07:53 UTC
When I attempt to download any of the natural earth II files, the request times out.

**Comment by berrely** [comment] 2021-09-02 09:40
Same, even with a download manager and 500mb/s internet it's timing out.
I get thrown this error:
```
Cannot download the file because of timeout

Details:
Cannot connect to naciscdn.org:443
```
Why aren't the downloads hosted on GitHub? Certainly, that'll be more reliable?

**Comment by berrely** [comment] 2021-09-02 09:44
Duplicate of #577

**Comment by nvkelso** [comment] 2021-09-07 04:51
Tracking this with https://github.com/nvkelso/natural-earth-vector/issues/581.

**Closed by nvkelso** 2021-09-07 04:51 UTC
