### ISSUE TITLE
Download link error

### ISSUE THREAD

**Issue by cubarro** [nvkelso/natural-earth-vector#598] opened 2021-09-20 14:50 UTC
I would like to download Small scale data, 1:110m.
Cultural option opens Download all 110m cultural themes 
This link in page shows
https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/110m/cultural/110m_cultural.zip

Which is an error.

I try to open http://www.naturalearthdata.com/download/110m/cultural/110m_cultural.zip and also get error.

Something is wrong today.

**Comment by nvkelso** [comment] 2021-09-21 07:08
Duplicate of https://github.com/nvkelso/natural-earth-vector/issues/581.

There's a [GIST](https://github.com/nvkelso/natural-earth-vector/issues/581#issuecomment-916250782) showing where to find the files in the meantime.

**Closed by nvkelso** 2021-09-21 07:08 UTC
