### ISSUE TITLE
1:10m Cultural Vectors

### ISSUE THREAD

**Issue by sohaismail** [nvkelso/natural-earth-vector#586] opened 2021-09-10 08:46 UTC
I am trying to download the 1:10m Cultural Vectors by they don't seem to be working. I get the error: "This site can't be reached"
https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/cultural/10m_cultural.zip

I am especially looking for populated places for city boundries, but I also get the same error
https://naciscdn.org/naturalearth/10m/cultural/ne_10m_populated_places.zip

**Comment by nvkelso** [comment] 2021-09-10 20:21
Duplicate of https://github.com/nvkelso/natural-earth-vector/issues/581

**Closed by nvkelso** 2021-09-10 20:21 UTC
