### ISSUE TITLE
The downloads on the website do not work !

### ISSUE THREAD

**Issue by EstebanOD** [nvkelso/natural-earth-vector#597] opened 2021-09-20 13:27 UTC
http://www.naturalearthdata.com/downloads/10m-raster-data/10m-cross-blend-hypso/
All the "Download large size" buttons do not work

**Comment by nvkelso** [comment] 2021-09-21 07:08
Duplicate of https://github.com/nvkelso/natural-earth-vector/issues/581.

There's a [GIST](https://github.com/nvkelso/natural-earth-vector/issues/581#issuecomment-916250782) showing where to find the files in the meantime.

**Closed by nvkelso** 2021-09-21 07:08 UTC
