### ISSUE TITLE
10m roads: Mexico, Cancún to Cozumel is "Ferry Route"

### ISSUE THREAD

**Issue by jwva** [nvkelso/natural-earth-vector#360] opened 2020-07-05 08:26 UTC
In the 10m roads, the "unknown" type road on water from Cancún to Cozumel should be of type "Ferry Route".

**Comment by nvkelso** [comment] 2021-03-03 04:23
I agree the **featurecla** should `Ferry` and the **type** should change to either `Ferry Route` or `Ferry, seasonal` based on further research (please comment sources). This is shown in "red" in the screenshot below.

There are 2 other shorter lines going to Cozumel from the mainland directly offshore. They both have different problems, but should match the **featurecla** and **type** above. These are shown in "yellow" in the screenshot below.

It looks like there are not **ne_id** property on the roads layer, hmm. We should file a followup issue for that (similar with problem for Ports theme).

![image](https://user-images.githubusercontent.com/853051/109752308-06d68e00-7b95-11eb-9dcd-0129dc03c3c8.png)

**Comment by elliotap** [comment] 2021-03-04 19:08
This is an interesting one - several tourism websites indicate that there is no ferry service between Cancun and San Miguel de Cozumel, and that the ferry service runs from Playa del Carmen. (https://scubamau.com/about-us/getting-here/ ; https://www.cancun-discounts.com/cozumel-ferry.htm ; https://www.cancun-shuttle-transportation.com/destinations/transportation-cancun-airport-to-cozumel). The sites do not indicate seasonality for the PDC-Cozumel ferry. I also called the Westin Lagunamar Ocean Resort Villas & Spa and spoke to a concierge who confirmed the information on the websites.

For the Cancun-San Miguel de Cozumel route, I propose removing the feature altogether. For the two lines going to from Playa Del Carmen-Cozumel, proposing attribute changes to featurecla=Ferry and type=Ferry Route

**Comment by nvkelso** [comment] 2021-03-04 19:52
Works for me.

**Comment by nvkelso** [comment] 2021-03-17 06:12
Fixed via #485.

**Closed by nvkelso** 2021-03-17 06:12 UTC
Labels: transport
