### ISSUE TITLE
This site can't be reached

### ISSUE THREAD

**Issue by mmapperr** [nvkelso/natural-earth-vector#589] opened 2021-09-12 09:35 UTC
Hi,

I am trying to download Shaded Relief, but see an error saying THIS SITE CAN'T BE REACHED. 

Can someone help PLEASE....!

Kind Regards

**Comment by almccon** [comment] 2021-09-13 17:39
See more discussion in #581

**Comment by mmapperr** [comment] 2021-09-13 23:47
Thanks aloot

**Comment by nvkelso** [comment] 2021-09-15 06:49
Dupe of https://github.com/nvkelso/natural-earth-vector/issues/581.

**Closed by nvkelso** 2021-09-15 06:49 UTC
