### ISSUE TITLE
Natural Earth map data are missing

### ISSUE THREAD

**Issue by atmsfer** [nvkelso/natural-earth-vector#583] opened 2021-09-08 18:08 UTC
The URL for the Natural Earth data is missing. Specifically, I am looking for https://naciscdn.org/naturalearth/10m/physical/ne_10m_land.zip, which is linked from http://www.naturalearthdata.com/downloads/10m-physical-vectors/. This crashes Cartopy maps.

**Comment by atmsfer** [comment] 2021-09-08 18:09
Repeat of prior issue.

**Comment by nvkelso** [comment] 2021-09-09 04:28
Duplicate of https://github.com/nvkelso/natural-earth-vector/issues/581.

**Closed by nvkelso** 2021-09-09 04:28 UTC
