### ISSUE TITLE
ISO_A2 codes -99

### ISSUE THREAD

**Issue by mathissen** [nvkelso/natural-earth-vector#570] opened 2021-08-04 08:27 UTC
Some countries have -99 ISO_A2 

Examples: Norway, France, Cyprus etc

**Comment by nvkelso** [comment] 2021-08-04 17:52
This is a dupe of #284, closing.

**Closed by nvkelso** 2021-08-04 17:52 UTC

**Comment by worc** [comment] 2022-10-05 22:47
That doesn't make any sense. Norway is `-99` everywhere, this is still an open bug.
