### ISSUE TITLE
Problem with some ISO Alpha-3 Country Codes

### ISSUE THREAD

**Issue by MrGranddy** [nvkelso/natural-earth-vector#348] opened 2020-05-20 10:33 UTC
Hello, I was working on a project with geopandas, which uses data from your repo. There is a problem with some of the country codes, for example France needs to be FRA and seemingly there are more.

More detailed discussion here, they have more examples, in my case I only worked with France:
https://github.com/geopandas/geopandas/issues/1041

**Comment by nvkelso** [comment] 2021-02-26 01:26
Dupe of https://github.com/nvkelso/natural-earth-vector/issues/284 and https://github.com/nvkelso/natural-earth-vector/issues/268, closing.

**Closed by nvkelso** 2021-02-26 01:26 UTC
Labels: adm0
