### ISSUE TITLE
admin-0  borders for Ukraine

### ISSUE THREAD

**Issue by devrand** [nvkelso/natural-earth-vector#628] opened 2021-11-12 13:29 UTC
In 2014 Russia occupied Crimea, part of Ukraine.
Admin-0 borders for Ukraine does not contain Crimea, even worse: Crimea is presented not even as a disputed territory but as a part of Russia (contrary for example to international law, i.e. there is a UN  General Assembly's approved resolution: https://en.wikipedia.org/wiki/United_Nations_General_Assembly_Resolution_68/262  )

So far only  Afghanistan, Cuba, North Korea, Kyrgyzstan, Nicaragua, Sudan, Syria, Zimbabwe and Natural Earth have recognised the result of the 2014 russian referendum in Crimea and accepted that it is a part of Russia.

**Comment by nvkelso** [comment] 2021-11-14 05:23
Hey @devrand. Thanks for your feedback. I understand the situation is complex. 

This issue is a duplicate of https://github.com/nvkelso/natural-earth-vector/issues/391, which has many more details including options to either downgrade your version of Natural Earth to version 3, or to modify version 4, and how version 5 will portray the situation with additional properties and files to match your expectations.

**Closed by nvkelso** 2021-11-14 05:23 UTC

**Comment by devrand** [comment] 2021-11-14 06:55
So with v5 will there be a default view with internationally recognized border of Ukraine, with occupied Crimea and part of Donbas as Ukraine? And some POI (non-default, including Russian?)

Please don't cite  a "on the ground" rule, as far as I can see this rule applied in one cases (Ukraine) and did not in others (Transnistria, Cyprus, Palestine etc)

**Comment by devrand** [comment] 2021-11-14 08:05
Last but not the least, I can make a pull request  if needed to change this situation.
