### ISSUE TITLE
I cant use and download from northearthdata site

### ISSUE THREAD

**Issue by saleh0007** [nvkelso/natural-earth-vector#599] opened 2021-09-22 22:02 UTC
hello 
I have a problem with northearthdata site.
Unfortunately, I cant download data I don't know where is problem.
he gives me this error message ( × Downloads on this server are broken. In the meantime, files are available to download at AWS.)
I don't know how can I solve it.
I need to help you and assets me to download data from the northearthdata site ( https://www.naturalearthdata.com/downloads/ )
best my regards.

**Comment by katabeta** [comment] 2021-09-22 22:56
Having similar issues with downloading from the website. The connection just times out without any errors. 

I believe all of the rasters and vectors are available on GitHub as a workaround (rasters: https://github.com/nvkelso/natural-earth-raster, vectors: https://github.com/nvkelso/natural-earth-vector).

**Comment by almccon** [comment] 2021-09-22 23:26
Duplicate of #581, there are also other workarounds using AWS S3 buckets listed in that issue.

**Closed** 2021-09-29 03:04 UTC
