### ISSUE TITLE
Non- Existing Lakes shown in Suriname, South America

### ISSUE THREAD

**Issue by GIS597** [nvkelso/natural-earth-vector#551] opened 2021-07-04 02:58 UTC
Dear all,
the natural earth data set contains two lakes in the west border areas of Suriname. there have been quite a few wrong maps of Suriname with these 2 Lake areas on them, they are incorrect. these 2 lakes do no exist. there is only 1 big lake in suriname, that is the one in the center, directly south of the City Paramaribo. can these 2 wrong lakes be removed from the dataset?
here is a link to a sample image, i have marked the wrong lakes with a red "X"
[https://ibb.co/0tYF438](https://ibb.co/0tYF438 )

**Comment by elliotap** [comment] 2021-08-14 09:44
see #342 @GIS597 could you provide feature IDs?

**Comment by GIS597** [comment] 2021-08-14 15:10
> see #342 @GIS597 could you provide feature IDs?

Feature ID# 664 and 1238, both do not exist. these projects were never started, strange how they ended up on so many Map databases.

**Comment by elliotap** [comment] 2021-08-19 06:37
Could be propagation of a misinterpretation of this series of maps, dating back to 1979? https://maps.lib.utexas.edu/maps/tpc/txu-pclmaps-oclc-22834566_l-28a.jpg  

Thanks for the info. I think this is a duplicate of #342 and that @MrGawsome has resolved it

**Closed** 2022-04-14 06:23 UTC
