### ISSUE TITLE
Unable to download files

### ISSUE THREAD

**Issue by EvaVermeylen** [nvkelso/natural-earth-vector#440] opened 2020-11-21 09:56 UTC
Dear

I am unable download any files from the website. When I click on the download link nothing happens...
How can this be solved?

Thank you for a quick answer!

**Comment by nvkelso** [comment] 2020-11-22 07:08
This should be resolved.

**Comment by nvkelso** [comment] 2020-11-22 07:08
Dupe of https://github.com/nvkelso/natural-earth-vector/issues/434

**Closed by nvkelso** 2020-11-22 07:08 UTC
