### ISSUE TITLE
Harney Peak, South Dakota is now named Black Elk Peak

### ISSUE THREAD

**Issue by almccon** [nvkelso/natural-earth-vector#438] opened 2020-11-20 23:09 UTC
The peak was officially renamed in August of 2016. Article in Indian Country Today: https://web.archive.org/web/20160812220454/http://indiancountrytodaymedianetwork.com/2016/08/12/breaking-black-elk-peak-soars-above-he-sapa-no-longer-harney-peak-165445

"The name Harney Peak has long been a source of anger and resentment for the Oceti Sakowin and the various treaty tribes."

The feature has been renamed in Wikidata, so perhaps it will be fixed automatically in the next Natural Earth release? https://www.wikidata.org/wiki/Q1585737

**Comment by elliotap** [comment] 2021-03-09 21:11
Confirmed - renamed in 2016 by US Board on Geographic Names (GNIS: https://geonames.usgs.gov/apex/f?p=GNISPQ:3:::NO::P3_FID:1261770)

Proposed edits:
Change name from Harney Peak to Black Elk Peak
Add name_alt of Harney Peak
Add wikidataid of Q1585737

**Comment by nvkelso** [comment] 2021-03-10 05:18
Works for me.

**Comment by nvkelso** [comment] 2021-04-15 21:32
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/497.

**Closed by nvkelso** 2021-04-15 21:32 UTC
Labels: physical
