### ISSUE TITLE
10m places: Adjust max population of Korla, China to 770,000

### ISSUE THREAD

**Issue by jwva** [nvkelso/natural-earth-vector#412] opened 2020-09-10 05:56 UTC
In Xinjiang Uygur Zizhiqu, China, the city of Korla (south of Ürümqi) is fast-growing: according to Wikipedia, the urban population was 770,000 in 2018. Please adjust in the 10m places table.

**Comment by elliotap** [comment] 2021-03-11 20:23
Validity unclear - wiki population and http://www.demographia.com/db-worldua.pdf indicate populations above 600k, while other publications indicate the population may be much smaller (see Financial Times: https://www.ft.com/content/fa6bd0b0-1d87-11ea-9186-7348c2f183af)

Adding further uncertainty to an accurate population count is the method of counting residents: 
"Alongside this rhetorical focus on the style of development, the vice director of the Urban Landscaping Department was also notably concerned with crude growth when he outlined the city’s 2005 development plan to me in 2008. He stated categorically that “the population of a city must keep increasing” – from the 2010 figure of 550,000 to at least 800,000 by 2015. Although this sounds like a tall order, almost half of the difference could be made up by reclassifying the temporary migrants who do not currently hold household registration in Korla." (https://journals.openedition.org/chinaperspectives/6249?file=1)

Adding even further uncertainty, a large number (possibly 1 million?) of Muslim people are interned by the government in hundreds to thousands of internment camps in the region in and around Korla (https://www.rfa.org/english/news/uyghur/jobs-08202020170719.html ; https://graphics.reuters.com/MUSLIMS-CAMPS-CHINA/010081G52NH/index.html) 

Propose tabling this issue until more clear population information is available about the place.

**Comment by nvkelso** [comment] 2021-03-14 17:31
I am okay updating the population of **Korla** to the DB-WorldUA value (in the 600 thousands)... but we'd need to update other cities in Xinjiang at the same time so the regional balance is maintained.

The prison complexes are tricky... the right thing to do count them towards the population of the populated area they are part of... but the problem is they origin city of the prisoners would need to be decremented by as much and we don't have any of those details. So let's ignore that detail for now.

**Comment by nvkelso** [comment] 2021-03-23 22:36
@elliotap Please audit other nearby cities and make recommendations on their population changes. Then reassign to @mizmay once there's a clear path forward.

**Comment by mizmay** [comment] 2021-04-05 05:42
I am following @elliotap and would be happy to include your best guess/reasoning (maybe it's just a very big range between POP_MIN and POP_MAX?) to https://github.com/nvkelso/natural-earth-vector/pull/508

**Comment by elliotap** [comment] 2021-04-06 00:29
Proposed below are population updates for cities surrounding Korla with best available numbers, with the caveat that I do not feel highly confident that these are precise numbers, but that the balance is right. First-hand census information was inaccessible/hard to find except through linked sources, often with dead links, and the numbers in the population column are for prefecture-level cities rather than urbanizations/seats. Where articles differentiated between "urban" and prefecture-level populations, POP_MAX tended to exceed the indicated "urban" population

On the other hand, the magnitude of population changes here generally aligns with reports of growth in Xinjiang province in the past decade, reported as ~3m growth from 2010-2018 (see, for example: https://www.chinadaily.com.cn/a/202101/07/WS5ff6a2e4a31024ad0baa1227.html) This update would increase sum of populations to the following cities by approximately 4m people, with 1.4 million of that coming from Urumqi, which has been well-documented so appears quite accurate (e.g. https://www.scmp.com/news/china/science/article/3127507/chinas-west-population-boom-could-drive-xinjiang-capital-bust)

City | ne_id | POP_MAX | Proposed Population | Raw Change | % Change | Notes
-- | -- | -- | -- | -- | -- | --
Aksu | 1159146973 | 340020 | 695000 | 354980 | 104.40% | pop from wikipedia
Hami | 1159150881 | 300848 | 580000 | 279152 | 92.79% | pop from wikipedia
Hotan | 1159150883 | 261730 | 408894 | 147164 | 56.23% | pop from wikipedia
Karamay | 1159146971 | 108769 | 261445 | 152676 | 140.37% | pop from wikipedia
Kashgar | 1159150885 | 543914 | 506640 | -37274 | -6.85% | pop from wikipedia
Korla | 1159146961 | 206373 | 613000 | 406627 | 197.03% | pop from DB world UA, aligns with wikipedia
Kuqa | 1159146965 | 111499 | 470600 | 359101 | 322.07% | pop from wikipedia
Quiemo | 1159140711 | 32494 | 65572 | 33078 | 101.80% | pop from wikipedia
Shache | 1159149875 | 373492 | 851374 | 477882 | 127.95% | pop from wikipedia
Shihezi | 1159146969 | 573182 | 640000 | 66818 | 11.66% | pop from wikipedia
Turpan | 1159140707 | 254900 | 651853 | 396953 | 155.73% | pop from wikipedia
Urumqi | 1159151531 | 2151000 | 3575000 | 1424000 | 66.20% | pop from wikipedia
Yining | 1159149877 | 403489 | 542507 | 139018 | 34.45% | pop from wikipedia

**Comment by nvkelso** [comment] 2021-04-06 04:52
These proposed values work for me, thanks @elliotap! Over to @mizmay :)

**Comment by mizmay** [comment] 2021-04-06 21:51
@elliotap @nvkelso Please advise on the specific transformation? Values in the "Proposed Population" column go to which column, and what additional modifications make sense for POP_MIN, POP_OTHER, etc?

**Comment by nvkelso** [comment] 2021-04-06 22:15
@mizmay please set **POP_MAX** to the `Proposed Population`, and leave the other columns alone for now.

**Comment by mizmay** [comment] 2021-04-07 02:39
AFTER

| SCALERANK| NATSCALE| LABELRANK|FEATURECLA      |NAME    |NAMEPAR |NAMEALT            |NAMEASCII | ADM0CAP|CAPIN | WORLDCITY| MEGACITY|SOV0NAME |SOV_A3 |ADM0NAME |ADM0_A3 |ADM1NAME       |ISO_A2 |NOTE | LATITUDE| LONGITUDE| POP_MAX| POP_MIN| POP_OTHER| RANK_MAX| RANK_MIN|MEGANAME         |LS_NAME | MAX_POP10| MAX_POP20| MAX_POP50| MAX_POP300| MAX_POP310| MAX_NATSCA| MIN_AREAKM| MAX_AREAKM| MIN_AREAMI| MAX_AREAMI| MIN_PERKM| MAX_PERKM| MIN_PERMI| MAX_PERMI| MIN_BBXMIN| MAX_BBXMIN| MIN_BBXMAX| MAX_BBXMAX| MIN_BBYMIN| MAX_BBYMIN| MIN_BBYMAX| MAX_BBYMAX| MEAN_BBXC| MEAN_BBYC|TIMEZONE     | UN_FID| POP1950| POP1955| POP1960| POP1965| POP1970| POP1975| POP1980| POP1985| POP1990| POP1995| POP2000| POP2005| POP2010| POP2015| POP2020| POP2025| POP2050| MIN_ZOOM|WIKIDATAID |     WOF_ID| CAPALT|NAME_EN        |NAME_DE      |NAME_ES         |NAME_FR         |NAME_PT |NAME_RU |NAME_ZH  |LABEL  |NAME_AR |NAME_BN |NAME_EL |NAME_HI |NAME_HU |NAME_ID |NAME_IT |NAME_JA |NAME_KO |NAME_NL |NAME_PL |NAME_SV |NAME_TR |NAME_VI |      NE_ID|
|---------:|--------:|---------:|:---------------|:-------|:-------|:------------------|:---------|-------:|:-----|---------:|--------:|:--------|:------|:--------|:-------|:--------------|:------|:----|--------:|---------:|-------:|-------:|---------:|--------:|--------:|:----------------|:-------|---------:|---------:|---------:|----------:|----------:|----------:|----------:|----------:|----------:|----------:|---------:|---------:|---------:|---------:|----------:|----------:|----------:|----------:|----------:|----------:|----------:|----------:|---------:|---------:|:------------|------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|--------:|:----------|----------:|------:|:--------------|:------------|:---------------|:---------------|:-------|:-------|:--------|:------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|----------:|
|         7|       20|         1|Populated place |Turpan  |NA      |NA                 |Turpan    |       0|NA    |         0|        0|China    |CHN    |China    |CHN     |Xinjiang Uygur |CN     |NA   | 42.93538|  89.16504|  651853|  102827|     97137|       10|        9|NA               |Turpan  |    102827|    102827|         0|          0|          0|         20|         34|         34|         13|         13|        63|        63|        39|        39|   89.11667|   89.11667|   89.23333|   89.23333|   42.90833|   42.90833|   42.98333|   42.98333|  89.17515|  42.94969|Asia/Urumqi  |      0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|      6.1|Q868527    |  890514681|      0|Turpan         |Turpan       |Turfán          |Tourfan         |Turpan  |Турфан  |吐鲁番   |NA     |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      | 1159140707|
|         7|       20|         1|Populated place |Quiemo  |NA      |NA                 |Quiemo    |       0|NA    |         0|        0|China    |CHN    |China    |CHN     |Xinjiang Uygur |CN     |NA   | 38.13376|  85.53332|   65572|   32494|     32341|        7|        7|NA               |Quiemo  |     32494|     32494|         0|          0|          0|         20|          8|          8|          3|          3|        13|        13|         8|         8|   85.51667|   85.51667|   85.55000|   85.55000|   38.12500|   38.12500|   38.15833|   38.15833|  85.53333|  38.14028|NA           |      0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|      6.1|Q3360588   | 1141907665|      0|Qiemo Town     |NA           |NA              |NA              |NA      |Черчен  |且末镇   |Quiemo |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      | 1159140711|
|         6|       30|         1|Populated place |Korla   |NA      |NA                 |Korla     |       0|NA    |         0|        0|China    |CHN    |China    |CHN     |Xinjiang Uygur |CN     |NA   | 41.73000|  86.15003|  613000|  179465|         0|       10|        9|NA               |Korla   |    206373|    206373|         0|          0|          0|         20|         33|         33|         13|         13|        40|        40|        25|        25|   86.09167|   86.09167|   86.17500|   86.17500|   41.72500|   41.72500|   41.80000|   41.80000|  86.13587|  41.76495|Asia/Urumqi  |      0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|      6.0|Q837425    |  102026827|      0|Korla          |Korla        |Korla           |Korla           |Korla   |Корла   |库尔勒   |NA     |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      | 1159146961|
|         6|       30|         1|Populated place |Kuqa    |NA      |NA                 |Kuqa      |       0|NA    |         0|        0|China    |CHN    |China    |CHN     |Xinjiang Uygur |CN     |NA   | 41.72775|  82.93637|  470600|   68105|    110513|        9|        8|NA               |Kuga    |    111499|         0|         0|          0|          0|         10|         30|         30|         11|         11|        44|        44|        27|        27|   82.90833|   82.90833|   83.02500|   83.02500|   41.68333|   41.68333|   41.74167|   41.74167|  82.96359|  41.71323|Asia/Urumqi  |      0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|      6.0|Q1023116   |  890511635|      0|Kuqa County    |Kuqa         |NA              |Kucha           |NA      |Куча    |库车县   |NA     |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      | 1159146965|
|         6|       30|         1|Populated place |Shihezi |NA      |NA                 |Shihezi   |       0|NA    |         0|        0|China    |CHN    |China    |CHN     |Xinjiang Uygur |CN     |NA   | 44.29997|  86.02993|  640000|  572772|    523626|       11|       11|NA               |Shihezi |    573182|         0|         0|          0|          0|         10|        220|        220|         85|         85|       172|       172|       107|       107|   85.90000|   85.90000|   86.13333|   86.13333|   44.20833|   44.20833|   44.42500|   44.42500|  86.01997|  44.33255|Asia/Urumqi  |      0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|      6.0|Q848680    |  890515727|      0|Shihezi        |Shihezi      |Shihezi         |Shihezi         |Shihezi |Шихэцзы |石河子   |NA     |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      | 1159146969|
|         6|       30|         1|Populated place |Karamay |NA      |NA                 |Karamay   |       0|NA    |         0|        0|China    |CHN    |China    |CHN     |Xinjiang Uygur |CN     |NA   | 45.58994|  84.85993|  261445|  108769|    108769|        9|        9|NA               |Karamay |    108769|    108769|         0|          0|          0|         20|         21|         21|          8|          8|        23|        23|        14|        14|   84.83333|   84.83333|   84.90000|   84.90000|   45.57500|   45.57500|   45.62500|   45.62500|  84.86393|  45.60131|NA           |      0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|      6.0|Q658240    | 1141908639|      0|Karamay        |Karamay      |Karamay         |Karamay         |Karamay |Карамай |克拉玛依 |NA     |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      | 1159146971|
|         6|       30|         1|Populated place |Aksu    |NA      |NA                 |Aksu      |       0|NA    |         0|        0|China    |CHN    |China    |CHN     |Xinjiang Uygur |CN     |NA   | 41.15001|  80.25003|  695000|  279389|    278233|       10|       10|NA               |Aksu    |    279389|    279389|         0|          0|          0|         20|         52|         52|         20|         20|        60|        60|        38|        38|   80.20833|   80.20833|   80.31667|   80.31667|   41.12500|   41.12500|   41.23333|   41.23333|  80.26979|  41.17021|Asia/Kashgar |      0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|      6.0|Q421648    |  890513771|      0|Aksu           |Aksu (Stadt) |Aksu            |Aksou           |Aksu    |Аксу    |阿克苏   |NA     |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      | 1159146973|
|         4|       50|         1|Populated place |Shache  |NA      |NA                 |Shache    |       0|NA    |         0|        0|China    |CHN    |China    |CHN     |Xinjiang Uygur |CN     |NA   | 38.42614|  77.25000|  851374|  191291|    191291|       10|        9|NA               |Shache  |    191433|    191433|    191433|          0|          0|         50|         38|         38|         15|         15|        49|        49|        31|        31|   77.20833|   77.20833|   77.30000|   77.30000|   38.38333|   38.38333|   38.46667|   38.46667|  77.25491|  38.42307|Asia/Kashgar |      0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|      5.6|Q857618    |  890513533|      0|Yarkant County |Yarkant      |Yarkanda        |Xian de Yarkand |Yarkand |Яркенд  |莎车县   |NA     |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      | 1159149875|
|         4|       50|         1|Populated place |Yining  |NA      |NA                 |Yining    |       0|NA    |         0|        0|China    |CHN    |China    |CHN     |Xinjiang Uygur |CN     |NA   | 43.90002|  81.35001|  542507|  403489|    385821|       10|       10|NA               |Yining  |    403489|    403489|    403489|          0|          0|         50|        102|        102|         39|         39|       130|       130|        81|        81|   81.23333|   81.23333|   81.42500|   81.42500|   43.87500|   43.87500|   44.01667|   44.01667|  81.32520|  43.93694|NA           |      0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|      5.1|Q866021    | 1141909243|      0|Yining City    |Gulja        |Gulja           |Yining          |Kuldja  |Кульджа |伊宁     |NA     |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      | 1159149877|
|         3|      110|         1|Populated place |Hami    |NA      |NA                 |Hami      |       0|NA    |         0|        0|China    |CHN    |China    |CHN     |Xinjiang Uygur |CN     |NA   | 42.82698|  93.51500|  580000|  137072|         0|       10|        9|NA               |Hami    |    300848|    300848|    300848|     300848|          0|        100|         41|         41|         16|         16|        50|        50|        31|        31|   93.45833|   93.45833|   93.57500|   93.57500|   42.77500|   42.77500|   42.87500|   42.87500|  93.51250|  42.82930|Asia/Urumqi  |      0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|      5.0|Q650585    |  102026833|      0|Yizhou         |Kumul        |Ciudad de Kumul |Yizhou          |Kumul   |Хами    |伊州区   |NA     |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      | 1159150881|
|         3|      110|         1|Populated place |Hotan   |NA      |NA                 |Hotan     |       0|NA    |         0|        0|China    |CHN    |China    |CHN     |Xinjiang Uygur |CN     |NA   | 37.09971|  79.92695|  408894|  114000|    230635|       10|        9|NA               |Hotan   |    261730|    261730|    261730|     261730|          0|        100|        110|        110|         43|         43|       133|       133|        83|        83|   79.75833|   79.75833|   79.95000|   79.95000|   37.08333|   37.08333|   37.28333|   37.28333|  79.86281|  37.17094|Asia/Kashgar |      0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|      4.0|Q235389    |  102026813|      0|Hotan          |Hotan        |Jotán           |Hotan           |Hotan   |Хотан   |和田     |NA     |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      | 1159150883|
|         3|      110|         1|Populated place |Kashgar |Kashi   |NA                 |Kashgar   |       0|NA    |         0|        0|China    |CHN    |China    |CHN     |Xinjiang Uygur |CN     |NA   | 39.47634|  75.96993|  506640|  400225|    481725|       11|       10|NA               |Kashi   |    543914|    543914|    497638|     543914|          0|        100|        190|        249|         74|         96|       222|       286|       138|       178|   75.87500|   75.87500|   76.22500|   76.22500|   39.38333|   39.38333|   39.53333|   39.58333|  76.05401|  39.47167|Asia/Kashgar |      0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|      5.0|Q170521    |  102026809|      0|Kashgar        |Kaxgar       |Kasgar          |Kachgar         |Kashgar |Кашгар  |喀什     |NA     |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      | 1159150885|
|         1|      300|         1|Admin-1 capital |Ürümqi  |NA      |rumqi&#124;Wulumqi |Urumqi    |       0|NA    |         0|        1|China    |CHN    |China    |CHN     |Xinjiang Uygur |CN     |NA   | 43.80696|  87.57306| 3575000| 1508225|   2044401|       12|       12|Cramqi (Wulumqi) |Urumqi  |   2066046|   2066046|   2066046|    2066046|          0|        100|        361|        361|        139|        139|       318|       318|       198|       198|   87.35833|   87.35833|   87.72500|   87.72500|   43.64167|   43.64167|   44.01667|   44.01667|  87.57849|  43.85453|Asia/Urumqi  |    118|     253|     312|     384|     472|     581|     715|     881|    1029|    1161|    1417|    1730|    2025|    2151|    2340|    2620|    2851|    3038|      3.7|Q16959     |  102026823|      0|Ürümqi         |Ürümqi       |Urumchi         |Ürümqi          |Ürümqi  |Урумчи  |乌鲁木齐 |NA     |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      | 1159151531|

**Comment by nvkelso** [comment] 2021-04-22 06:38
Fixed via #508 and https://github.com/nvkelso/natural-earth-vector/commit/54a661943db3e228e28d0ce756fc173aff87c0f5 to reapply #5.

**Closed by nvkelso** 2021-04-22 06:38 UTC
Labels: pop_places
