### ISSUE TITLE
Natural Earth Downloads

### ISSUE THREAD

**Issue by AlyDVT** [nvkelso/natural-earth-vector#592] opened 2021-09-15 02:26 UTC
Downloads aren't working, I get the following error message "DNS_PROBE_FINISHED_NXDOMAIN"

**Comment by nvkelso** [comment] 2021-09-15 06:49
Dupe of https://github.com/nvkelso/natural-earth-vector/issues/581

**Closed by nvkelso** 2021-09-15 06:49 UTC
