### ISSUE TITLE
Download links are down

### ISSUE THREAD

**Issue by natcase** [nvkelso/natural-earth-vector#594] opened 2021-09-17 00:54 UTC
Links on https://www.naturalearthdata.com/downloads/10m-raster-data/10m-natural-earth-1/ are not working.

Also, to report this error, I had to log into github, something not every user will be able to do.

**Comment by nvkelso** [comment] 2021-09-17 07:09
Duplicate of https://github.com/nvkelso/natural-earth-vector/issues/581. There's a GIST in the comments with all the new recommended links.

**Closed by nvkelso** 2021-09-17 07:09 UTC
