### ISSUE TITLE
Scaleranks of island countries changed between 4.0 and 4.1

### ISSUE THREAD

**Issue by jirik** [nvkelso/natural-earth-vector#282] opened 2018-11-29 12:50 UTC
When I was considering to upgrade NE within OpenMapTiles project from v4.0 to v4.1, I found very different scaleranks of some countries between NE 4.0 and 4.1. For example:

| country | scalerank 4.0 | scalerank 4.1 |
| --- | --- | --- |
| Philippines | 0 | 6 |
| New Zeland | 0 | 6 |
| Indonesia | 0 | 5 |
| Malaysia | 0 | 5 |
| Cyprus | 1 | 6 |

All of them are island countries.

I am not sure if this was intentional change, but it seems to me more as a bug. It seems to be caused by this commit: https://github.com/nvkelso/natural-earth-vector/commit/a632044a316fff77916ea3822126544a8cf4eedd#diff-500e41b5546b247f4d8db8384b2eaa6a

**Comment by nvkelso** [comment] 2018-11-29 16:42
That's odd, I'll have a look.

But you should consider switching to the `min_zoom` and the `min_label` columns, they are curated for web mapping.

**Comment by nvkelso** [comment] 2021-02-14 06:33
@jirik @pathmapper can you confirm this is in the 1:10m countries theme in Natural Earth, please?

**Comment by pathmapper** [comment] 2021-02-14 07:51
@nvkelso just confirmed the scale ranks in the table of https://github.com/nvkelso/natural-earth-vector/issues/282#issue-385721775

Yes, this is 1:10m countries theme (`ne_10m_admin_0_countries`).
`4.0` data from: 
https://github.com/nvkelso/natural-earth-vector/archive/v4.0.0.zip
`4.1` data from: 
https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/cultural/ne_10m_admin_0_countries.zip

**Comment by nvkelso** [comment] 2021-03-08 07:48
The root cause of this is eluding me, punting to v5.1 as it's not a breaking change.

**Comment by nvkelso** [comment] 2021-05-29 06:23
Ah, this is because Mapshaper's dissolve grabs the "first" random scalerank. By adding a `-calc` flag I can insist the `min` scalerank be used instead.

**Comment by nvkelso** [comment] 2021-05-29 06:35
Fixed via 41bc7e5370e686ec57f2bd645ea1c4b2c7733bf2.

**Closed by nvkelso** 2021-05-29 06:35 UTC
Labels: adm0
