### ISSUE TITLE
Scotland Sea in Japan is obviously wrong

### ISSUE THREAD

**Issue by mits003** [nvkelso/natural-earth-vector#703] opened 2022-03-25 07:34 UTC
I found a miss-named marine area in Japan.
It is named `Inner seas off the West Coast of Scotland` but it should be following
name_en = `Seto Island Sea`
name_ja = `瀬戸内海`

Could you tell me how do I make a PR, please?

![スクリーンショット 2022-03-25 15 41 00](https://user-images.githubusercontent.com/43772370/160074698-2b8bfc47-ec92-4663-96ad-b64f700630a6.png)

**Comment by Kanahiro** [comment] 2022-03-25 08:07
FYI

Inner Seas off the West Coast of Scotland
https://en.wikipedia.org/wiki/Inner_Seas_off_the_West_Coast_of_Scotland

Seto Island Sea
https://en.wikipedia.org/wiki/Seto_Inland_Sea

**Comment by nvkelso** [comment] 2022-03-31 05:32
Duplicate of https://github.com/nvkelso/natural-earth-vector/issues/665. Closing this one in favor of that one for tracking purposes.

**Closed by nvkelso** 2022-03-31 05:32 UTC
