### ISSUE TITLE
broken links (1:110m Cultural Vectors - Admin 0 – Countries)

### ISSUE THREAD

**Issue by leomiquelutti** [nvkelso/natural-earth-vector#584] opened 2021-09-08 18:15 UTC
Dear,

the links under the **Admin 0 – Countries** section, in the [downloads of the 110m cultural vectors](https://www.naturalearthdata.com/downloads/110m-cultural-vectors/) seems to be broken.

Best regards,

**Comment by nvkelso** [comment] 2021-09-09 04:29
Duplicate of https://github.com/nvkelso/natural-earth-vector/issues/581.

**Closed by nvkelso** 2021-09-09 04:29 UTC
