### ISSUE TITLE
Separate metropolitan from overseas territories (France, Norway...)

### ISSUE THREAD

**Issue by perrette** [nvkelso/natural-earth-vector#315] opened 2020-01-25 19:29 UTC
The description on the website says:

> There are 247 countries in the world. Greenland as separate from Denmark. Most users will want this file instead of sovereign states.

However France includes oversea territories (e.g. French Guyana) and Norway includes Svalbard.
This sounds contrary to the description, and indeed suboptimal for cartography. 

I suggest to separate these territories.

**Comment by perrette** [comment] 2020-01-25 19:50
I see in the properties:
    ('WOE_NOTE', 'Includes only Metropolitan France (including Corsica)'),

But the geometry is made from 10 polygons well in the Southern Atlantic (down to 21S, 61E) , I think French Guyana is in. Only Corsica should be attached.

**Comment by nvkelso** [comment] 2021-06-14 06:00
Closing as not to be fixed, as designed.

The country of France in Natural Earth doesn't have a WOE concordance, but it does have a WOE_EH concordance (which is to say there is a fuzzy match on what Natural Earth considers France and what Where on Earth considers France. That's what the note is saying, that it's fuzzy and that WOE has a different definition, but many people would find the WOE one more useful so that's included in WOE_EH.

This is because the overseas areas of USA and France admin hierarchies need to be treated the same in Natural Earth.

If you want just metropolitan France (with or without Corsica) look in the map units and map subunit themes instead.

**Closed by nvkelso** 2021-06-14 06:00 UTC
Labels: adm0
